apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: monitor-apm-server
  name: monitor-apm-server
spec:
  ports:
  - name: "8200"
    port: 8200
    targetPort: 8200
  selector:
    app.kubernetes.io/name: monitor-apm-server
status:
  loadBalancer: {}
