apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: monitor-apm-server
  name: monitor-apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: monitor-apm-server
  strategy: {}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: monitor-apm-server
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: monitor-configmap-apm
        image: elastic/apm-server:7.6.0
        imagePullPolicy: ""
        name: monitor-apm-server
        ports:
        - containerPort: 8200
        resources: {}
        command:
          - "apm-server"
          - "-e"
          - "-E"
          - "apm-server.host=${HOST}"
          - "-E"
          - "apm-server.secret_token=${SECRET_TOKEN}"
          - "-E"
          - "logging.to_files=${LOGGING_TO_FILES}"
          - "-E"
          - "output.elasticsearch.hosts=${ELASTICSEARCH_HOSTS}"
          - "-E"
          - "setup.kibana.host=${KIBANA_HOST}"
          - "-E"
          - "setup.template.enabled=${TEMPLATE_ENABLED}"
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
