apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-configmap-logstash
data:
  PIPELINE_WORKERS: '{{ .Values.LOGSTASH_PIPELINE_WORKERS }}'
  CONFIG_STRING: '{{ .Values.LOGSTASH_CONFIG_STRING }}'
  XPACK_MONITORING_ELASTICSEARCH_HOSTS: '{{ .Values.LOGSTASH_XPACK_MONITORING_ELASTICSEARCH_HOSTS }}'
