apiVersion: v1
kind: ConfigMap
metadata:
  name: monitor-configmap-elasticsearch
data:
  ES_JAVA_OPTS: '{{ .Values.ELASTICSEARCH_ES_JAVA_OPTS }}'
  JAVA_TOOL_OPTIONS: '{{ .Values.ELASTICSEARCH_JAVA_TOOL_OPTIONS }}'
  discovery.type: '{{ .Values.ELASTICSEARCH_DISCOVERY_TYPE }}'
