apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: monitor-elasticsearch
  name: monitor-elasticsearch
spec:
  ports:
  - name: "9200"
    port: 9200
    targetPort: 9200
  selector:
    app.kubernetes.io/name: monitor-elasticsearch
status:
  loadBalancer: {}
