apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitor-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /monitor/kibana/?(.*)
          pathType: Prefix
          backend:
            service:
              name: monitor-kibana
              port:
                number: 5601
