FROM python:3.8-buster
COPY ./nlp_service /app/nlp_service
COPY ./news_service_lib /app/news_service_lib

WORKDIR /app/news_service_lib
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN python setup.py bdist_wheel
RUN pip install dist/news_service_lib-0.0.1-py3-none-any.whl

WORKDIR /app

RUN wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | apt-key add -
RUN apt-get install apt-transport-https -y
RUN echo "deb https://artifacts.elastic.co/packages/7.x/apt stable main" | tee -a /etc/apt/sources.list.d/elastic-7.x.list
RUN apt-get update && apt-get install metricbeat

RUN pip install --upgrade pip
RUN pip install -r nlp_service/requirements_celery.txt

COPY ./nlp_service/tools_config/metricbeat-celery.yml /etc/metricbeat/metricbeat.yml

CMD service metricbeat start && export PYTHONPATH=${PYTHONPATH}:/app && python ./nlp_service/nlp_celery_worker/celery_app.py -p DOCKER