apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: apm-server
  name: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apm-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: apm-server
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-service-monitor-configmap
        image: store/elastic/apm-server:7.6.0
        imagePullPolicy: ""
        name: apm-server
        ports:
        - containerPort: 8200
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
