apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-service-monitor-configmap
        image: elasticsearch:7.6.0
        imagePullPolicy: ""
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elastic-news-service-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: elastic-news-service-data
        persistentVolumeClaim:
          claimName: elastic-news-service-data
status: {}
