apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c -f docker\news-service.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c -f docker\news-service.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-service-monitor-configmap
        image: elasticsearch:7.6.0
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - curl -s -f http://localhost:9200/_cluster/health
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elastic-news-service-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: elastic-news-service-data
        persistentVolumeClaim:
          claimName: elastic-news-service-data
status: {}
