apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c -f docker\news-service.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: heartbeat
  name: heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heartbeat
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c -f docker\news-service.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: heartbeat
    spec:
      containers:
      - image: djrevok/heartbeat-news-service:latest
        imagePullPolicy: ""
        name: heartbeat
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
