apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: heartbeat
  name: heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heartbeat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: heartbeat
    spec:
      containers:
      - image: djrevok/heartbeat-news-service:latest
        imagePullPolicy: ""
        name: heartbeat
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
