apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: news-service-monitor-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
          - path: /kibana/?(.*)
              backend:
                service:
                  name: kibana
                  port:
                    number: 5601
          - path: /flower/?(.*)
              backend:
                service:
                  name: news-service-flower
                  port:
                    number: 5555