apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
      convert -c -f docker\news-service.yml
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\ProgramData\chocolatey\lib\kubernetes-kompose\tools\kompose.exe
          convert -c -f docker\news-service.yml
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: news-service-monitor-configmap
        image: rabbitmq:management
        imagePullPolicy: ""
        livenessProbe:
          exec:
            command:
            - rabbitmq-diagnostics -q ping
          failureThreshold: 3
          periodSeconds: 30
          timeoutSeconds: 30
        name: rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 15674
        - containerPort: 25672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
