version: '3'

services:
  mongodb-first:
    image: djrevok/mongo-first-news-service:latest
    command: "--replSet nsrs"
    volumes:
      - 'mongodb_news_first_data:/data/db'
    ports:
      - "27017:27017"
    depends_on:
      - elasticsearch
      - kibana

  mongodb-second:
    image: djrevok/mongo-second-news-service:latest
    command: "--port 27018 --replSet nsrs"
    volumes:
      - 'mongodb_news_second_data:/data/db'
    ports:
      - "27018:27018"
    depends_on:
      - elasticsearch
      - kibana

  mysql-uaa:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - 'mysql_uaa_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: n3wss3rv1c3
      MYSQL_DATABASE: uaa
      MYSQL_USER: app-us3r
      MYSQL_PASSWORD: n3wsp4ssw0rd
    ports:
      - "3306:3306"

  mysql-search-engine:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - 'mysql_search_engine_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: n3wss3rv1c3
      MYSQL_DATABASE: search-engine
      MYSQL_USER: app-us3r
      MYSQL_PASSWORD: n3wsp4ssw0rd
    ports:
      - "3307:3306"

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
    volumes:
      - elastic_news_service_data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  logstash:
    build:
      context: logstash
    image: logstash-news-service:latest
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"

  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash

  apm-server:
    image: store/elastic/apm-server:7.6.0
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: 'http://elasticsearch:9200'
      apm-server.host: "0.0.0.0:8200"
      apm-server.secret_token: "xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      setup.kibana.host: "kibana:5601"
      setup.template.enabled: "true"
      logging.to_files: "false"
    depends_on:
      - elasticsearch
      - kibana

  rabbitmq:
    image: rabbitmq:management
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
      RABBITMQ_DEFAULT_VHOST: /
    ports:
      - 4369:4369
      - 5671:5671
      - 5672:5672
      - 15671:15671
      - 15672:15672
      - 15674:15674
      - 25672:25672

  redis:
    image: 'bitnami/redis:latest'
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379
    volumes:
      - redis_data:/bitnami/redis/data


volumes:
  mongodb_news_first_data:
  mongodb_news_second_data:
  mysql_uaa_data:
  mysql_search_engine_data:
  elastic_news_service_data:
  redis_data:
