version: '3'

services:
  mongodb:
    build:
      context: mongo
    image: mongo-news-service:latest
    volumes:
      - 'mongodb_data:/data/db'
    ports:
      - "27017:27017"
    depends_on:
      - elasticsearch
      - kibana

  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    volumes:
    - 'mysql_data:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: n3wss3rv1c3
      MYSQL_DATABASE: newsservice
      MYSQL_USER: app-us3r
      MYSQL_PASSWORD: n3wsp4ssw0rd
    ports:
      - "3306:3306"

  uaa:
    build:
      context: ../
      dockerfile: uaa/Dockerfile
    image: uaa:latest
    ports:
      - "8081:8081"
    depends_on:
      - mysql
      - logstash
      - apm-server
      - elasticsearch
      - kibana

  news-manager:
    build:
      context: ../
      dockerfile: news_manager/Dockerfile
    image: news-manager:latest
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
      - logstash
      - apm-server
      - elasticsearch
      - kibana
      - uaa

  elasticsearch:
    image: elasticsearch:7.6.0
    ports:
      - "9200:9200"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    environment:
      JAVA_TOOL_OPTIONS: "-Xms512m -Xmx512m"
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      discovery.type: "single-node"

  logstash:
    build:
      context: logstash
    image: logstash-news-service:latest
    depends_on:
      - elasticsearch
    ports:
      - "5000:5000"

  kibana:
    image: kibana:7.6.0
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
      - logstash

  apm-server:
    image: store/elastic/apm-server:7.6.0
    ports:
      - "8200:8200"
    environment:
      output.elasticsearch.hosts: 'http://elasticsearch:9200'
      apm-server.host: "0.0.0.0:8200"
      apm-server.secret_token: "xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44"
      setup.kibana.host: "kibana:5601"
      setup.template.enabled: "true"
      logging.to_files: "false"
    depends_on:
      - elasticsearch
      - kibana

  heartbeat:
    build:
      context: heartbeat
    image: heartbeat-news-service:latest
    depends_on:
      - elasticsearch
      - kibana
      - news-manager
      - uaa

volumes:
  mongodb_data:
  mysql_data:
  elastic_data:
