news-manager:
  NEWS_MANAGER_SERVER__HOST: 0.0.0.0
  NEWS_MANAGER_SERVER__PORT: 8080

  NEWS_MANAGER_MONGO__HOST: news-manager-mongo
  NEWS_MANAGER_MONGO__PORT: 27017
  NEWS_MANAGER_MONGO__DATABASE: news-manager

  NEWS_MANAGER_ELASTIC_APM__SECRET_TOKEN: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  NEWS_MANAGER_ELASTIC_APM__URL: http://monitor-apm-server:8200

  NEWS_MANAGER_REDIS__HOST: redis-master
  NEWS_MANAGER_REDIS__PORT: 6379
  NEWS_MANAGER_REDIS__PASSWORD: test_password

  NEWS_MANAGER_RABBIT__HOST: rabbitmq
  NEWS_MANAGER_RABBIT__PORT: 5672
  NEWS_MANAGER_RABBIT__PASSWORD: test_password
  NEWS_MANAGER_RABBIT__USER: test_user

  NEWS_MANAGER_RPYC_GET_NEW_HOST: news-manager-get-new
  NEWS_MANAGER_RPYC_GET_NEW_PORT: 10000

  NEWS_MANAGER_ELASTICSEARCH_HOSTS: monitor-elasticsearch:9200
  NEWS_MANAGER_LOGSTASH_HOSTS: monitor-logstash:5044
  NEWS_MANAGER_KIBANA_HOST: monitor-kibana:5601
