search-engine:
  SEARCH_ENGINE_SERVER__HOST: 0.0.0.0
  SEARCH_ENGINE_SERVER__PORT: 8081

  SEARCH_ENGINE_STORAGE__HOST: search-engine-postgres
  SEARCH_ENGINE_STORAGE__PORT: 5432
  SEARCH_ENGINE_STORAGE__USER: app-user
  SEARCH_ENGINE_STORAGE__PASSWORD: app-user-password
  SEARCH_ENGINE_STORAGE__DATABASE: search-engine

  SEARCH_ENGINE_ELASTIC_APM__SECRET_TOKEN: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
  SEARCH_ENGINE_ELASTIC_APM__URL: http://monitor-apm-server:8200

  SEARCH_ENGINE_REDIS__HOST: redis-master
  SEARCH_ENGINE_REDIS__PORT: 6379
  SEARCH_ENGINE_REDIS__PASSWORD: test_password

  SEARCH_ENGINE_RABBIT__HOST: rabbitmq
  SEARCH_ENGINE_RABBIT__PORT: 5672
  SEARCH_ENGINE_RABBIT__PASSWORD: test_password
  SEARCH_ENGINE_RABBIT__USER: test_user

  SEARCH_ENGINE_IAM_JWKS_PATH: http://iam-web-server:8888/jwks

  SEARCH_ENGINE_ELASTICSEARCH_HOSTS: monitor-elasticsearch:9200
  SEARCH_ENGINE_LOGSTASH_HOSTS: monitor-logstash:5044
  SEARCH_ENGINE_KIBANA_HOST: monitor-kibana:5601

  SEARCH_ENGINE_POSTGRES_DB: search-engine
  SEARCH_ENGINE_POSTGRES_USER: app-user
  SEARCH_ENGINE_POSTGRES_PASSWORD: app-user-password
