heartbeat.monitors:
- type: http
  schedule: '@every 5s'
  urls:
    - http://event-manager:8080/healthcheck
    - http://uaa:8081/healthcheck

output.elasticsearch:
  hosts: ['elasticsearch:9200']

setup.kibana:
  host: 'kibana:5601'