apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbit-configmap
data:
  RABBITMQ_DEFAULT_PASS: '{{ .Values.global.RABBITMQ_DEFAULT_PASS }}'
  RABBITMQ_DEFAULT_USER: '{{ .Values.global.RABBITMQ_DEFAULT_USER }}'
  RABBITMQ_DEFAULT_VHOST: '{{ .Values.global.RABBITMQ_DEFAULT_VHOST }}'
