{{ if .Values.enabled }}

apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbitmq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: rabbitmq
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: rabbit-configmap
        image: rabbitmq:management
        imagePullPolicy: ""
        name: rabbitmq
        ports:
        - containerPort: 4369
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 15672
        - containerPort: 15674
        - containerPort: 25672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}

{{ end }}