apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: apm-server
  name: apm-server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: apm-server
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: apm-server
    spec:
      containers:
      - env:
        - name: apm-server.host
          value: 0.0.0.0:8200
        - name: apm-server.secret_token
          value: xxVpmQB2HMzCL9PgBHVrnxjNXXw5J7bd79DFm6sjBJR5HPXDhcF8MSb3vv4bpg44
        - name: logging.to_files
          value: "false"
        - name: output.elasticsearch.hosts
          value: http://elasticsearch:9200
        - name: setup.kibana.host
          value: kibana:5601
        - name: setup.template.enabled
          value: "true"
        image: store/elastic/apm-server:7.6.0
        imagePullPolicy: ""
        name: apm-server
        ports:
        - containerPort: 8200
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
