apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: elasticsearch
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - env:
        - name: ES_JAVA_OPTS
          value: -Xms512m -Xmx512m
        - name: JAVA_TOOL_OPTIONS
          value: -Xms512m -Xmx512m
        - name: discovery.type
          value: single-node
        image: elasticsearch:7.6.0
        imagePullPolicy: ""
        name: elasticsearch
        ports:
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: elastic-news-service-data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: elastic-news-service-data
        persistentVolumeClaim:
          claimName: elastic-news-service-data
status: {}
