apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../docker/docker-compose.yml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: heartbeat
  name: heartbeat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: heartbeat
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../docker/docker-compose.yml
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: heartbeat
    spec:
      containers:
      - image: heartbeat-event-service:latest
        imagePullPolicy: IfNotPresent
        name: heartbeat
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
