apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: news-service-fanout
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - http:
        paths:
        - path: /manager/?(.*)
          backend:
            serviceName: news-manager
            servicePort: 8080
        - path: /uaa/?(.*)
          backend:
            serviceName: uaa
            servicePort: 8081
        - path: /nlp/?(.*)
          backend:
            serviceName: nlp-service
            servicePort: 8082
        - path: /kibana/?(.*)
          backend:
            serviceName: kibana
            servicePort: 5601
        - path: /flower/?(.*)
          backend:
            serviceName: nlp-service-flower
            servicePort: 5555