resources:
  - mongodb-service.yaml
  - mongodb-deployment.yaml
  - mongodb-news-data-persistentvolumeclaim.yaml
  - mysql-service.yaml
  - mysql-deployment.yaml
  - mysql-uaa-data-persistentvolumeclaim.yaml
  - uaa-service.yaml
  - uaa-deployment.yaml
  - news-manager-service.yaml
  - news-manager-deployment.yaml
  - elasticsearch-service.yaml
  - elasticsearch-deployment.yaml
  - elastic-news-service-data-persistentvolumeclaim.yaml
  - logstash-service.yaml
  - logstash-deployment.yaml
  - kibana-service.yaml
  - kibana-deployment.yaml
  - apm-server-service.yaml
  - apm-server-deployment.yaml
  - heartbeat-deployment.yaml
  - nlp-celery-worker-deployment.yaml
  - nlp-service-deployment.yaml
  - nlp-service-service.yaml
  - nlp-service-flower-deployment.yaml
  - nlp-service-flower-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - ingress.yaml