resources:
  - mongodb-first-service.yaml
  - mongodb-first-deployment.yaml
  - mongodb-news-first-data-persistentvolumeclaim.yaml
  - mongodb-second-service.yaml
  - mongodb-second-deployment.yaml
  - mongodb-news-second-data-persistentvolumeclaim.yaml
  - mysql-uaa-service.yaml
  - mysql-uaa-deployment.yaml
  - mysql-uaa-data-persistentvolumeclaim.yaml
  - redis-service.yaml
  - redis-deployment.yaml
  - redis-data-persistentvolumeclaim.yaml
  - mysql-search-engine-service.yaml
  - mysql-search-engine-deployment.yaml
  - mysql-search-engine-data-persistentvolumeclaim.yaml
  - uaa-service.yaml
  - uaa-deployment.yaml
  - news-manager-service.yaml
  - news-manager-deployment.yaml
  - news-discovery-app-deployment.yaml
  - news-discovery-beat-deployment.yaml
  - search-engine-service.yaml
  - search-engine-deployment.yaml
  - elasticsearch-service.yaml
  - elasticsearch-deployment.yaml
  - elastic-news-service-data-persistentvolumeclaim.yaml
  - logstash-service.yaml
  - logstash-deployment.yaml
  - kibana-service.yaml
  - kibana-deployment.yaml
  - apm-server-service.yaml
  - apm-server-deployment.yaml
  - heartbeat-deployment.yaml
  - nlp-celery-worker-deployment.yaml
  - news-service-flower-deployment.yaml
  - news-service-flower-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - ingress.yaml
  - ingress-rabbit.yaml