apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: news-discovery-beat
  name: news-discovery-beat
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: news-discovery-beat
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: news-discovery-beat
    spec:
      containers:
      - env:
        - name: CELERY_FORCE_ROOT
          value: "True"
        image: djrevok/news-discovery-beat:latest
        imagePullPolicy: ""
        name: news-discovery-beat
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
