apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nlp-service
  name: nlp-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nlp-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nlp-service
    spec:
      containers:
      - env:
        - name: JWT_SECRET
          value: t0k3ns3cr3t
        - name: SERVER_BASEPATH
          value: "/nlp"
        image: djrevok/nlp-service:latest
        imagePullPolicy: ""
        name: nlp-service
        ports:
        - containerPort: 8082
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
