apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: nlp-service-flower
  name: nlp-service-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nlp-service-flower
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ./docker/docker-compose.yml -o kubernetess/resources
        kompose.version: 1.21.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: nlp-service-flower
    spec:
      containers:
      - env:
        - name: RABBIT_URL_PREFIX
          value: rabbit
        - name: URL_PREFIX
          value: flower
        image: djrevok/nlp-service-flower:latest
        imagePullPolicy: ""
        name: nlp-service-flower
        ports:
        - containerPort: 5555
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
