name: News Service Release Process

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version of the release to create'
        required: true

jobs:
  news-discovery-release:
    runs-on: ubuntu-latest

    steps:
      - name: Validate version
        uses: rubenesp87/semver-validation-action@0.0.6
        with:
          version: ${{ github.event.inputs.version }}
      - name: Check if version exists
        uses: mukunku/tag-exists-action@v1.0.0
        id: checkTag
        with:
          tag: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup helm
        uses: azure/setup-helm@v1
      - name: Build helm chart
        run: make build_chart version=${{ github.event.inputs.version }}
      - name: Clone helm repo
        run: |
          git clone https://DeejayRevok:${{ secrets.HELM_REPO_ACCESS_TOKEN }}@github.com/DeejayRevok/helm-repo.git
      - name: Copy chart to repo
        run: cp ./news-service-${{ github.event.inputs.version }}.tgz ./helm-repo
      - name: Index new chart
        run: helm repo index --url https://deejayrevok.github.io/helm-repo ./helm-repo
      - name: Push new chart
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Github Actions Automatically Built News Service Release ${{ steps.get_version.outputs.version }}"
          git push --force --quiet https://DeejayRevok:${{ secrets.HELM_REPO_ACCESS_TOKEN }}@github.com/DeejayRevok/helm-repo.git main:main
        working-directory: ./helm-repo
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
