name: News Service Release Process

on:
  push:
    branches:
      - master

jobs:
  news-service-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Get version
        id: get_version
        run: |
          VERSION=`cat VERSION`
          echo "Version: $VERSION"
          echo "::set-output name=version::$VERSION"
      - name: Setup helm
        uses: azure/setup-helm@v3
        with:
          version: 'v3.5.4'
      - name: Build helm chart
        run: make build_news_service_chart
      - name: Clone helm repo
        run: |
          git clone https://DeejayRevok:${{ secrets.HELM_REPO_ACCESS_TOKEN }}@github.com/DeejayRevok/helm-repo.git
      - name: Copy chart to repo
        run: cp ./news-service-${{ steps.get_version.outputs.version }}.tgz ./helm-repo
      - name: Index new chart
        run: helm repo index --url https://deejayrevok.github.io/helm-repo ./helm-repo
      - name: Push new chart
        run: |
          git config --local user.name "Github Action"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git commit -m "Github Actions Automatically Built News Service Release ${{ steps.get_version.outputs.version }}"
          git push --force --quiet https://DeejayRevok:${{ secrets.HELM_REPO_ACCESS_TOKEN }}@github.com/DeejayRevok/helm-repo.git main:main
        working-directory: ./helm-repo
      - uses: avakar/tag-and-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
